[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes (unused vars, imports)
    "D",    # pydocstyle (docstrings required)
    "N",    # pep8-naming (function/variable naming)
    "C90",  # McCabe complexity
    "ARG",  # unused arguments
    "I",    # isort (import sorting)
]
ignore = []

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pycodestyle]
max-line-length = 200  # Max lines per function

[tool.ruff.lint.isort]
force-sort-within-sections = true
case-sensitive = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
